### ISSUE TITLE
disposeOnTap: true: It doesn't work.

### ISSUE THREAD

**Issue by braysonjohn148** [SimformSolutionsPvtLtd/flutter_showcaseview#89]
WidgetsBinding.instance.addPostFrameCallback((_) => ShowCaseWidget.of(context).startShowCase([_one]));

`floatingActionButton:  Showcase(  
                              disposeOnTap: true,
                              onTargetClick: (){......
                             });
`

I tried: WidgetsBinding.instance.addPostFrameCallback((_) => ShowCaseWidget.of(context).dispose());
After failing.

**Comment by DevarshRanpara** [comment]
Hi @braysonjohn148 ,
Can you elaborate your bug in detail?

**Comment by vatsaltanna** [comment]
Hello Guys,

We recently have released a new version of the showcase view package `showcaseview: ^1.1.0`. please try the new version. Your problem should have been solved in the new release.

**Comment by vatsaltanna** [comment]
Feel free to reopen if it is still happening for you.

**Comment by kamami** [comment]
Same issue with the latest version. Sometimes in works, sometimes it still shows the overlay after navigating.


```
            Showcase(
                  key: _six,
                  disposeOnTap: true,
                  onTargetClick: route.polylines.length > 0 ? selectRoute : () => print(""),
                  child: TextButton(
                            child: Text("Navigate"),
                             onPressed: onPressed: route.polylines.length > 0
                                                 ? () => selectRoute()
                                                  : () => print(""),
                            )
               )
```
